# -*- coding: utf-8 -*-
"""The app's colour themes (#278): one table, two templates.

Roberto's brief of 6 Sep 2026: a reader picks a theme, and the sun-and-moon
toggle switches light and dark *within* it. Navy is the default and is the
page exactly as it was; the other twelve are the palettes he approved on
the rendered sheet kept in Notes/themes_2026-09-06/.

Each theme is twenty-two values -- five for the banner, seven for the
results panel, ten per mode for the page -- and everything else the two
stylesheets need (the soft rule, the code background, the note tint, the
placeholder, the focus ring ...) is derived from those here, the same way
for every theme, so a new theme is a row in TABLE and nothing else.

    python tools/palettes.py write    # regenerate the blocks in both templates
    python tools/palettes.py check    # fail if either block is stale

The blocks sit between the markers below. build_local.py runs `check` on
every build, so a hand edit inside the markers is caught rather than kept.

Navy deliberately has no block: it is the templates' own :root and
html[data-theme="dark"], untouched, and `data-palette` is simply absent
from the root element. That is what keeps today's page byte-for-byte the
default. The dark-mode button hover was #1f4a86 in both modes until this
item -- the light theme's dark blue on a #5b96e0 button -- and Navy's dark
block now says #4a86d0; that one line is Navy's whole change.
"""
from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
CR, LF = chr(13), chr(10)
SERVER = HERE.parent
TEMPLATES = ["templates/index.html", "templates/eqsheet.html"]

BEGIN = "/* ==== BEGIN palettes (#278) ==== generated by tools/palettes.py; do not edit */"
END = "/* ==== END palettes (#278) ==== */"

# key, English name (the dictionaries carry the translations under
# js.palette.<key>), then the twenty-two values in the sheet's order:
#   banner: top band, ribbon, numeral + keyline, subtitle, ribbon link
#   panel:  gradient top, ground, border, row line, readout ink, dim, name
#   light:  ground, card, ink, muted, accent, accent ink, rule, field,
#           field border, button hover
#   dark:   the same ten
# The order of TABLE is the menu's order: chromatic, Navy first as the
# default, High contrast last as the one achromatic theme.
TABLE = [
    ("navy", "Default",
     "#203864 #2a4576 #8ec7f5 #b7c3d6 #dbe6f5",
     "#102338 #0d1e30 #081525 #173352 #8ecbff #4a7098 #6fb8f0",
     "#f4f6fa #ffffff #1c2330 #5b6472 #2f5fa8 #ffffff #e2e5ea #fbfcfd #cfd6df #1f4a86",
     "#12161d #1b212c #e4e8ee #97a3b6 #5b96e0 #0d1420 #2b3341 #11161e #38424f #4a86d0"),
    ("violet", "Violet",
     "#363a80 #42478f #b9bdff #bfc1e6 #e0e1f8",
     "#1b1d44 #14163a #0a0b22 #2b2e60 #c6c5ff #6b6ca8 #a3a1ff",
     "#f5f5fc #ffffff #1f1f38 #5f6180 #5652c8 #ffffff #e0e1f0 #fbfbff #cbcde6 #4340a8",
     "#13142a #1c1d38 #e7e7f6 #9c9ec4 #9d9bff #12132a #2d2f52 #0f1024 #3b3d66 #b4b2ff"),
    ("pastels", "Pastels",
     "#7f74ad #8d83b8 #ffe9a8 #ece7f7 #f6f3fc",
     "#47406c #3e3860 #2e2a48 #565080 #c8f5dc #9a93bf #f7c7d9",
     "#f8f6fb #ffffff #3a3550 #7a7494 #e79ab0 #3a3550 #e8e3f2 #fcfbfe #d8d1e8 #f0b0c2",
     "#221f30 #2c2840 #ece8f5 #aaa3c4 #f2b8c8 #221f30 #3f3a56 #1d1a2a #4c4666 #f8cbd8"),
    ("warmpink", "Warm Pink",
     "#5c1a45 #6c2654 #f3a6d3 #d9b3cb #f3dbe9",
     "#2b0f22 #21091a #12050e #43203a #ffb6de #8a5a78 #f08cc4",
     "#fbf5f8 #ffffff #2a1a24 #6f5866 #b02a72 #ffffff #ecdde5 #fdfafc #dcc6d3 #8f1f5b",
     "#1a1015 #24161f #f2e6ed #ad93a3 #ea6fb4 #1a1015 #3a2833 #160d12 #4a3341 #f08cc4"),
    ("burgundy", "Burgundy",
     "#4f1424 #5f1d30 #f0a9b8 #d4aab4 #f3dae0",
     "#2a0c14 #200810 #100408 #44182a #ffb8c6 #8c5868 #f28aa0",
     "#faf4f5 #ffffff #2c1a1f #6f5860 #8c1d38 #ffffff #ebdde0 #fdfafb #dcc6cb #6e1329",
     "#1a1114 #251a1e #f2e6e9 #ad949b #e3708c #1a1114 #3c2a30 #150e11 #4c373e #ee92a8"),
    ("brick", "Brick",
     "#6a2c20 #7b392c #f4b79e #d8b3a6 #f5e1da",
     "#2d1611 #23100c #120705 #4a2820 #ffbfa6 #8f5c4c #f39678",
     "#faf4f1 #fffdfc #2e1c17 #715a53 #a53f2b #ffffff #ecdcd6 #fdfaf8 #dcc6bf #86311f",
     "#1b1210 #261915 #f1e4df #b0958c #e27a5e #1b1210 #3d2a25 #160e0c #4e3730 #ee9a82"),
    ("earth", "Earth",
     "#4a3a2a #594736 #dcbb87 #cdbca4 #ecdfcc",
     "#2a2016 #201810 #100b07 #43352a #eacd9e #8a7250 #d7b078",
     "#f8f4ee #fffdf9 #2d2419 #6f6152 #8a5a2b #ffffff #e6dccf #fdfaf5 #d5c8b6 #6e4620",
     "#1a1512 #241d18 #ede4d8 #ab9c8a #d3a262 #1a1512 #3a3028 #15100d #4a3e33 #e2b87d"),
    ("graygold", "Gray & Gold",
     "#3b4048 #484e57 #d9aa4c #b8bec6 #e2e6ea",
     "#23282e #1a1e22 #0d0f11 #343a41 #f0c070 #7d7466 #d9aa4c",
     "#f2f3f4 #ffffff #1e2125 #5f666e #b3781e #ffffff #dde0e3 #fafbfb #c8cdd3 #8f5e14",
     "#141618 #1d2023 #e6e8ea #9aa1a8 #e0a83c #141618 #2d3135 #101214 #3d4247 #f0bd5e"),
    ("firefly", "Firefly",
     "#0a1810 #122419 #e3f56b #8fb09a #d2e8c8",
     "#0e2418 #081a10 #030d07 #1a3a26 #e8ff7a #4e7a56 #b9ec5c",
     "#f1f5ee #fbfdf8 #16261b #52685a #4f7f21 #ffffff #d5e1d3 #f7faf4 #bdd0bf #3d6418",
     "#070f0a #0d1a12 #d9ecd2 #7fa088 #d6f253 #0a1a10 #1c3324 #050b07 #23402c #e8ff7a"),
    ("forest", "Forest",
     "#1e3d2b #294a36 #a8d8a0 #b3c9b8 #dcebdf",
     "#14301f #0f2418 #061209 #1f4430 #b8ecb8 #5a8a66 #8fd49a",
     "#f3f7f3 #fffefc #172519 #566b5a #2c6e42 #ffffff #dbe6dc #fbfdfb #c6d8c9 #215532",
     "#0f1712 #16221a #e4eee5 #92ab97 #6cc488 #0f1712 #26362b #0c130e #33473a #8ad8a1"),
    ("turquoise", "Turquoise",
     "#0f4a58 #175a69 #7fe3d6 #a9d3cf #d6f1ec",
     "#0b2f36 #08252b #041418 #164048 #8ef0e2 #3f8a84 #5fd6c8",
     "#f4f8f5 #fffefb #14302e #56706c #0f8a82 #ffffff #dbe8e3 #fbfdfb #c4d9d3 #0b6d67",
     "#0e1b1c #142628 #e3f0ec #8fb2ac #45d0c2 #0a1a1a #23393a #0b1617 #2f4a4b #6ee0d4"),
    ("highcontrast", "Contrast",
     "#000000 #111111 #ffd400 #dddddd #ffffff",
     "#000000 #000000 #ffffff #444444 #ffffff #bbbbbb #ffd400",
     "#ffffff #ffffff #000000 #333333 #0000c8 #ffffff #000000 #ffffff #000000 #000080",
     "#000000 #000000 #ffffff #dddddd #ffd400 #000000 #ffffff #000000 #ffffff #ffe866"),
]

KEYS = [row[0] for row in TABLE]
NAMES = dict((row[0], row[1]) for row in TABLE)


# --- colour arithmetic ------------------------------------------------------

def _rgb(h: str) -> tuple:
    h = h.lstrip("#")
    return tuple(int(h[i:i + 2], 16) for i in (0, 2, 4))


def _hex(rgb) -> str:
    return "#%02x%02x%02x" % tuple(max(0, min(255, int(round(c)))) for c in rgb)


def mix(a: str, b: str, t: float) -> str:
    """a moved t of the way towards b."""
    ra, rb = _rgb(a), _rgb(b)
    return _hex(tuple(x + (y - x) * t for x, y in zip(ra, rb)))


def rgba(h: str, alpha: float) -> str:
    return "rgba(%d,%d,%d,%s)" % (_rgb(h) + (alpha,))


def rgb_list(h: str) -> str:
    return "%d,%d,%d" % _rgb(h)


# --- the theme record --------------------------------------------------------

def theme(row) -> dict:
    key, name, banner, panel, light, dark = row
    b = banner.split()
    p = panel.split()
    modes = {}
    for mode, values in (("light", light), ("dark", dark)):
        v = values.split()
        modes[mode] = dict(zip(
            ("bg", "card", "ink", "muted", "accent", "accent_ink", "line",
             "field", "field_line", "hover"), v))
    return dict(
        key=key, name=name,
        navy=b[0], navy2=b[1], sky=b[2], sub=b[3], link=b[4],
        lcd_top=p[0], lcd_bg=p[1], lcd_border=p[2], lcd_line=p[3],
        lcd_ink=p[4], lcd_dim=p[5], lcd_name=p[6],
        light=modes["light"], dark=modes["dark"],
    )


THEMES = [theme(r) for r in TABLE]


def _decl(pairs) -> str:
    return "".join("    %s: %s;\n" % kv for kv in pairs)


# --- the app page (index.html) ------------------------------------------------

def app_page_vars(t: dict, m: dict, mode: str) -> list:
    """The page's own tokens for one mode, in the order :root declares them."""
    return [
        ("--bg", m["bg"]), ("--card", m["card"]), ("--ink", m["ink"]),
        ("--muted", m["muted"]), ("--accent", m["accent"]),
        ("--accent-ink", m["accent_ink"]),
        ("--accent-open", mix(m["accent"], m["card"] if mode == "dark" else m["ink"], 0.15)),
        ("--accent-hover", m["hover"]),
        ("--line", m["line"]), ("--line-soft", mix(m["line"], m["bg"], 0.5)),
        ("--placeholder", mix(m["muted"], m["bg"], 0.45)),
        ("--focus-line", m["accent"]),
        ("--focus-ring", "0 0 0 3px " + rgba(m["accent"], 0.18)),
        ("--btn-disabled", mix(m["muted"], m["bg"], 0.5)),
        ("--solve-shadow-rgb", rgb_list(m["hover"])),
        ("--field-bg", m["field"]), ("--field-bg-focus", m["card"]),
        ("--field-border", m["field_line"]),
        ("--field-border-hover", mix(m["field_line"], m["ink"], 0.3)),
        ("--code-bg", mix(m["card"], m["line"], 0.55)),
        ("--note-bg", mix(m["card"], m["accent"], 0.08)),
        ("--note-line", mix(m["card"], m["accent"], 0.4)),
    ]


def app_shared_vars(t: dict) -> list:
    """The banner and the results panel: the same in both modes."""
    return [
        ("--navy", t["navy"]), ("--navy-2", t["navy2"]), ("--sky", t["sky"]),
        ("--banner-sub", t["sub"]), ("--banner-link", t["link"]),
        ("--lcd-top", t["lcd_top"]), ("--lcd-bg", t["lcd_bg"]),
        ("--lcd-border", t["lcd_border"]), ("--lcd-line", t["lcd_line"]),
        ("--lcd-ink", t["lcd_ink"]), ("--lcd-dim", t["lcd_dim"]),
        ("--lcd-name", t["lcd_name"]),
        ("--lcd-scroll", mix(t["lcd_line"], t["lcd_ink"], 0.3)),
        ("--lcd-glow", "transparent" if t["key"] == "highcontrast"
                       else rgba(t["lcd_name"], 0.10)),
    ]


def app_block() -> str:
    out = []
    for t in THEMES:
        if t["key"] == "navy":
            continue
        sel = 'html[data-palette="%s"]' % t["key"]
        out.append("  /* %s */\n" % t["name"])
        out.append("  %s {\n%s  }\n" % (
            sel, _decl(app_shared_vars(t) + app_page_vars(t, t["light"], "light"))))
        out.append('  %s[data-theme="dark"] {\n%s  }\n' % (
            sel, _decl(app_page_vars(t, t["dark"], "dark"))))
        if t["key"] == "graygold":
            # The one theme with a gradient: a brushed sheen on the bands.
            out.append("  %s .topbar { background: linear-gradient(180deg, #4a5059 0%%, %s 70%%); }\n"
                       % (sel, t["navy"]))
            out.append("  %s .subbar { background: linear-gradient(180deg, %s 0%%, #40454e 100%%); }\n"
                       % (sel, t["navy2"]))
        if t["key"] == "highcontrast":
            out.append("  %s .lcd, %s .elcard, %s .card { box-shadow: none; }\n"
                       % (sel, sel, sel))
    return "".join(out)


# --- the Numerical Solver page (eqsheet.html) ----------------------------------

def eq_page_vars(t: dict, m: dict, mode: str) -> list:
    return [
        ("--paper", m["bg"]), ("--card", m["card"]),
        ("--card-2", mix(m["card"], m["bg"], 0.5)),
        ("--ink", m["ink"]), ("--ink-2", m["muted"]),
        ("--ink-3", mix(m["muted"], m["bg"], 0.4)),
        ("--line", m["line"]), ("--rule-2", mix(m["line"], m["bg"], 0.5)),
        ("--accent", m["accent"]),
        ("--result-ink", m["hover"] if mode == "light" else m["accent"]),
        ("--badge-bg", mix(m["card"], m["line"], 0.55)),
        ("--lcd", m["field"]), ("--lcd-edge", m["field_line"]),
    ]


def eq_block() -> str:
    out = []
    for t in THEMES:
        if t["key"] == "navy":
            continue
        sel = 'html[data-palette="%s"]' % t["key"]
        shared = [("--navy", t["navy"]), ("--navy-2", t["navy2"]),
                  ("--sky", t["sky"]), ("--banner-sub", t["sub"]),
                  ("--banner-link", t["link"])]
        out.append("  /* %s */\n" % t["name"])
        out.append("  %s {\n%s  }\n" % (sel, _decl(shared + eq_page_vars(t, t["light"], "light"))))
        out.append('  %s[data-theme="dark"] {\n%s  }\n' % (sel, _decl(eq_page_vars(t, t["dark"], "dark"))))
        if t["key"] == "graygold":
            out.append("  %s .topbar { background: linear-gradient(180deg, #4a5059 0%%, %s 70%%); }\n"
                       % (sel, t["navy"]))
            out.append("  %s .subbar { background: linear-gradient(180deg, %s 0%%, #40454e 100%%); }\n"
                       % (sel, t["navy2"]))
    return "".join(out)


BLOCKS = {"templates/index.html": app_block, "templates/eqsheet.html": eq_block}


def splice(text: str, body: str, rel: str) -> str:
    i, j = text.find(BEGIN), text.find(END)
    if i < 0 or j < 0 or j < i:
        raise SystemExit("palettes.py: the palette markers are missing from %s" % rel)
    return text[:i + len(BEGIN)] + "\n" + body + "  " + text[j:]


def run(write: bool) -> list:
    problems = []
    for rel, make in BLOCKS.items():
        path = SERVER / rel
        raw = path.read_bytes()
        # eqsheet.html is CRLF and index.html LF; each keeps its own.
        crlf = (CR + LF).encode() in raw
        nl = CR + LF if crlf else LF
        text = raw.decode("utf-8").replace(CR + LF, LF)
        want = splice(text, make(), rel)
        if want != text:
            if write:
                path.write_text(want, encoding="utf-8", newline=nl)
                print("palettes.py: wrote the block in %s" % rel)
            else:
                problems.append("%s: the palette block is stale -- run "
                                "`python tools/palettes.py write`" % rel)
    return problems


def main() -> int:
    cmd = sys.argv[1] if len(sys.argv) > 1 else "check"
    if cmd not in ("write", "check"):
        print(__doc__)
        return 2
    problems = run(write=(cmd == "write"))
    for p in problems:
        print(p)
    if cmd == "check":
        print("palettes check:", "ok" if not problems else "%d problem(s)" % len(problems))
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
